name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - publish
      - master
      - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: var1
    value: 2
    
resources:
  repositories:
    - repository: destination
      type: git
      name: TEST_CONSENTINO/destination
      #ref: master
      ref: develop
stages:
  - stage: first
    displayName: First
    jobs:
      - job: first
        displayName: 'First'
        steps:
            - checkout: self
            - checkout: destination
              persistCredentials: true
            - task: bash@3
              name: run_script
              inputs:
                targetType: 'inline'
                script: |
                  pwd
                  ls -l
                  cd test-repo && git fetch && git checkout publish
                  
                  git config --global user.email "azure_devops@example.com"
                  git config --global user.name "Azure DevOps Pipeline"
                  echo "Entering into 'destination'"
                  cd ../destination 
                  echo "Checkout develop"
                  
                  git switch -c feature/release-1.0
                  echo "Copying files form test-repo to destination"
                  pwd
                  ls -l ../test-repo
                  ls -l
                  cp -R ../test-repo/* .
                  ls -l
                  echo "get status"
                  git status
                  echo "Adding files to repository"
                  git add . && git commit -m "Azure DevOps" && git push --set-upstream origin feature/release-1.0
                  echo "Finishing"
              displayName: 'Hello'
