name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - publish
      - master
      - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: var1
    value: 2
    
resources:
  repositories:
    - repository: destination
      type: git
      name: TEST_CONSENTINO/destination
      #ref: master
      ref: develop
stages:
  - stage: first
    displayName: First
    jobs:
      - job: first
        displayName: 'First'
        steps:
            - checkout: self
            - checkout: destination
            - task: bash@3
              name: run_script
              inputs:
                targetType: 'inline'
                script: |
                  ls -l
                  cd test-repo && git fetch && git checkout publish
                  
                  git config --global user.email "azure_devops@example.com"
                  git config --global user.name "Azure DevOps Pipeline"
                  cd ../destination 
                  git fetch && git checkout develop
                  cp -R ../destination .
                  git add . && git commit -m "Azure DevOps" && git push
                  echo "Hello GitHub"
              displayName: 'Hello'
